use crate::invoke;

#[derive(Copy, Clone)]
pub enum Group {
    Move,
    Look,
    Wheel,
    CellphoneNavigate,
    CellphoneNavigateUpDown,
    CellphoneNavigateLeftRight,
    FrontendDpadAll,
    FrontendDpadUpDown,
    FrontendDpadLeftRight,
    FrontendLStickAll,
    FrontendRStickAll,
    FrontendGenericUpDown,
    FrontendGenericLeftRight,
    FrontendGenericAll,
    FrontendBumpers,
    FrontendTriggers,
    FrontendSticks,
    ScriptDpadAll,
    ScriptDpadUpDown,
    ScriptDpadLeftRight,
    ScriptLStickAll,
    ScriptRStickAll,
    ScriptBumpers,
    ScriptTriggers,
    WeaponWheelCycle,
    Fly,
    Sub,
    VehicleMoveAll,
    Cursor,
    CursorScroll,
    SniperZoomSecondary,
    VehicleHydraulicsControl,
    MaxInputGroups,
    Invalid,
}

#[derive(Copy, Clone)]
pub enum Control {
    NextCamera,
    LookLeftRight,
    LookUpDown,
    LookUpOnly,
    LookDownOnly,
    LookLeftOnly,
    LookRightOnly,
    CinematicSlowMo,
    FlyUpDown,
    FlyLeftRight,
    ScriptedFlyZUp,
    ScriptedFlyZDown,
    WeaponWheelUpDown,
    WeaponWheelLeftRight,
    WeaponWheelNext,
    WeaponWheelPrev,
    SelectNextWeapon,
    SelectPrevWeapon,
    SkipCutscene,
    CharacterWheel,
    MultiplayerInfo,
    Sprint,
    Jump,
    Enter,
    Attack,
    Aim,
    LookBehind,
    Phone,
    SpecialAbility,
    SpecialAbilitySecondary,
    MoveLeftRight,
    MoveUpDown,
    MoveUpOnly,
    MoveDownOnly,
    MoveLeftOnly,
    MoveRightOnly,
    Duck,
    SelectWeapon,
    Pickup,
    SniperZoom,
    SniperZoomInOnly,
    SniperZoomOutOnly,
    SniperZoomInSecondary,
    SniperZoomOutSecondary,
    Cover,
    Reload,
    Talk,
    Detonate,
    HUDSpecial,
    Arrest,
    AccurateAim,
    Context,
    ContextSecondary,
    WeaponSpecial,
    WeaponSpecial2,
    Dive,
    DropWeapon,
    DropAmmo,
    ThrowGrenade,
    VehicleMoveLeftRight,
    VehicleMoveUpDown,
    VehicleMoveUpOnly,
    VehicleMoveDownOnly,
    VehicleMoveLeftOnly,
    VehicleMoveRightOnly,
    VehicleSpecial,
    VehicleGunLeftRight,
    VehicleGunUpDown,
    VehicleAim,
    VehicleAttack,
    VehicleAttack2,
    VehicleAccelerate,
    VehicleBrake,
    VehicleDuck,
    VehicleHeadlight,
    VehicleExit,
    VehicleHandbrake,
    VehicleHotwireLeft,
    VehicleHotwireRight,
    VehicleLookBehind,
    VehicleCinCam,
    VehicleNextRadio,
    VehiclePrevRadio,
    VehicleNextRadioTrack,
    VehiclePrevRadioTrack,
    VehicleRadioWheel,
    VehicleHorn,
    VehicleFlyThrottleUp,
    VehicleFlyThrottleDown,
    VehicleFlyYawLeft,
    VehicleFlyYawRight,
    VehiclePassengerAim,
    VehiclePassengerAttack,
    VehicleSpecialAbilityFranklin,
    VehicleStuntUpDown,
    VehicleCinematicUpDown,
    VehicleCinematicUpOnly,
    VehicleCinematicDownOnly,
    VehicleCinematicLeftRight,
    VehicleSelectNextWeapon,
    VehicleSelectPrevWeapon,
    VehicleRoof,
    VehicleJump,
    VehicleGrapplingHook,
    VehicleShuffle,
    VehicleDropProjectile,
    VehicleMouseControlOverride,
    VehicleFlyRollLeftRight,
    VehicleFlyRollLeftOnly,
    VehicleFlyRollRightOnly,
    VehicleFlyPitchUpDown,
    VehicleFlyPitchUpOnly,
    VehicleFlyPitchDownOnly,
    VehicleFlyUnderCarriage,
    VehicleFlyAttack,
    VehicleFlySelectNextWeapon,
    VehicleFlySelectPrevWeapon,
    VehicleFlySelectTargetLeft,
    VehicleFlySelectTargetRight,
    VehicleFlyVerticalFlightMode,
    VehicleFlyDuck,
    VehicleFlyAttackCamera,
    VehicleFlyMouseControlOverride,
    VehicleSubTurnLeftRight,
    VehicleSubTurnLeftOnly,
    VehicleSubTurnRightOnly,
    VehicleSubPitchUpDown,
    VehicleSubPitchUpOnly,
    VehicleSubPitchDownOnly,
    VehicleSubThrottleUp,
    VehicleSubThrottleDown,
    VehicleSubAscend,
    VehicleSubDescend,
    VehicleSubTurnHardLeft,
    VehicleSubTurnHardRight,
    VehicleSubMouseControlOverride,
    VehiclePushbikePedal,
    VehiclePushbikeSprint,
    VehiclePushbikeFrontBrake,
    VehiclePushbikeRearBrake,
    MeleeAttackLight,
    MeleeAttackHeavy,
    MeleeAttackAlternate,
    MeleeBlock,
    ParachuteDeploy,
    ParachuteDetach,
    ParachuteTurnLeftRight,
    ParachuteTurnLeftOnly,
    ParachuteTurnRightOnly,
    ParachutePitchUpDown,
    ParachutePitchUpOnly,
    ParachutePitchDownOnly,
    ParachuteBrakeLeft,
    ParachuteBrakeRight,
    ParachuteSmoke,
    ParachutePrecisionLanding,
    Map,
    SelectWeaponUnarmed,
    SelectWeaponMelee,
    SelectWeaponHandgun,
    SelectWeaponShotgun,
    SelectWeaponSmg,
    SelectWeaponAutoRifle,
    SelectWeaponSniper,
    SelectWeaponHeavy,
    SelectWeaponSpecial,
    SelectCharacterMichael,
    SelectCharacterFranklin,
    SelectCharacterTrevor,
    SelectCharacterMultiplayer,
    SaveReplayClip,
    SpecialAbilityPC,
    PhoneUp,
    PhoneDown,
    PhoneLeft,
    PhoneRight,
    PhoneSelect,
    PhoneCancel,
    PhoneOption,
    PhoneExtraOption,
    PhoneScrollForward,
    PhoneScrollBackward,
    PhoneCameraFocusLock,
    PhoneCameraGrid,
    PhoneCameraSelfie,
    PhoneCameraDOF,
    PhoneCameraExpression,
    FrontendDown,
    FrontendUp,
    FrontendLeft,
    FrontendRight,
    FrontendRDown,
    FrontendRUp,
    FrontendRLeft,
    FrontendRRight,
    FrontendAxisX,
    FrontendAxisY,
    FrontendRightAxisX,
    FrontendRightAxisY,
    FrontendPause,
    FrontendPauseAlternate,
    FrontendAccept,
    FrontendCancel,
    FrontendX,
    FrontendY,
    FrontendLb,
    FrontendRb,
    FrontendLt,
    FrontendRt,
    FrontendLs,
    FrontendRs,
    FrontendLeaderboard,
    FrontendSocialClub,
    FrontendSocialClubSecondary,
    FrontendDelete,
    FrontendEndScreenAccept,
    FrontendEndScreenExpand,
    FrontendSelect,
    ScriptLeftAxisX,
    ScriptLeftAxisY,
    ScriptRightAxisX,
    ScriptRightAxisY,
    ScriptRUp,
    ScriptRDown,
    ScriptRLeft,
    ScriptRRight,
    ScriptLB,
    ScriptRB,
    ScriptLT,
    ScriptRT,
    ScriptLS,
    ScriptRS,
    ScriptPadUp,
    ScriptPadDown,
    ScriptPadLeft,
    ScriptPadRight,
    ScriptSelect,
    CursorAccept,
    CursorCancel,
    CursorX,
    CursorY,
    CursorScrollUp,
    CursorScrollDown,
    EnterCheatCode,
    InteractionMenu,
    MpTextChatAll,
    MpTextChatTeam,
    MpTextChatFriends,
    MpTextChatCrew,
    PushToTalk,
    CreatorLS,
    CreatorRS,
    CreatorLT,
    CreatorRT,
    CreatorMenuToggle,
    CreatorAccept,
    CreatorDelete,
    Attack2,
    RappelJump,
    RappelLongJump,
    RappelSmashWindow,
    PrevWeapon,
    NextWeapon,
    MeleeAttack1,
    MeleeAttack2,
    Whistle,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    LookLeft,
    LookRight,
    LookUp,
    LookDown,
    SniperZoomIn,
    SniperZoomOut,
    SniperZoomInAlternate,
    SniperZoomOutAlternate,
    VehicleMoveLeft,
    VehicleMoveRight,
    VehicleMoveUp,
    VehicleMoveDown,
    VehicleGunLeft,
    VehicleGunRight,
    VehicleGunUp,
    VehicleGunDown,
    VehicleLookLeft,
    VehicleLookRight,
    ReplayStartStopRecording,
    ReplayStartStopRecordingSecondary,
    ScaledLookLeftRight,
    ScaledLookUpDown,
    ScaledLookUpOnly,
    ScaledLookDownOnly,
    ScaledLookLeftOnly,
    ScaledLookRightOnly,
    ReplayMarkerDelete,
    ReplayClipDelete,
    ReplayPause,
    ReplayRewind,
    ReplayFFWD,
    ReplayNewMarker,
    ReplayRecord,
    ReplayScreenshot,
    ReplayHideHud,
    ReplayStartPoint,
    ReplayEndpoint,
    ReplayAdvance,
    ReplayBack,
    ReplayTools,
    ReplayRestart,
    ReplayShowHotkey,
    ReplayCycleMarkerLeft,
    ReplayCycleMarkerRight,
    ReplayFOVIncrease,
    ReplayFOVDecrease,
    ReplayCameraUp,
    ReplayCameraDown,
    ReplaySave,
    ReplayToggleTime,
    ReplayToggleTips,
    ReplayPreview,
    ReplayToggleTimeline,
    ReplayTimelinePickupClip,
    ReplayTimelineDuplicateClip,
    ReplayTimelinePlaceClip,
    ReplayCtrl,
    ReplayTimelineSave,
    ReplayPreviewAudio,
    VehicleDriveLook,
    VehicleDriveLook2,
    VehicleFlyAttack2,
    RadioWheelUpDown,
    RadioWheelLeftRight,
    VehicleSlowMoUpDown,
    VehicleSlowMoUpOnly,
    VehicleSlowMoDownOnly,
    MapPointOfInterest,
    ReplaySnapmaticPhoto,
    VehicleCarJump,
    VehicleRocketBoost,
    VehicleParachute,
    VehicleBikeWings,
    VehicleFlyBombBay,
    VehicleFlyCounter,
    VehicleFlyTransform,
}

pub fn disable_action(group: Group, control: Control, disable: bool) {
    invoke!((), 0xFE99B66D079CF6BC, group as u32, control as u32, disable)
}

pub fn enable_action(group: Group, control: Control, enable: bool) {
    invoke!((), 0x351220255D64C155, group as u32, control as u32, enable)
}

pub fn disable_all_actions(group: Group) {
    invoke!((), 0x5F4B6931816E599B, group as u32)
}

pub fn enable_all_actions(group: Group) {
    invoke!((), 0xA5FFE9B05F199DE7, group as u32)
}

pub fn is_enabled(group: Group, control: Control) -> bool {
    invoke!(bool, 0x1CEA6BFDF248E5D9, group as u32, control as u32)
}

pub fn is_released(group: Group, control: Control) -> bool {
    invoke!(bool, 0x648EE3E7F38877DD, group as u32, control as u32)
}

pub fn is_pressed(group: Group, control: Control) -> bool {
    invoke!(bool, 0xF3A21BCD95725A4A, group as u32, control as u32)
}

pub fn is_just_pressed(group: Group, control: Control) -> bool {
    invoke!(bool, 0x580417101DDB492F, group as u32, control as u32)
}

pub fn is_just_released(group: Group, control: Control) -> bool {
    invoke!(bool, 0x50F940259D3841E6, group as u32, control as u32)
}

pub fn is_disabled_pressed(group: Group, control: Control) -> bool {
    invoke!(bool, 0xE2587F8CBBD87B1D, group as u32, control as u32)
}

pub fn is_disabled_released(group: Group, control: Control) -> bool {
    invoke!(bool, 0xFB6C4072E9A32E92, group as u32, control as u32)
}

pub fn is_disabled_just_pressed(group: Group, control: Control) -> bool {
    invoke!(bool, 0x91AEF906BCA88877, group as u32, control as u32)
}

pub fn is_disabled_just_released(group: Group, control: Control) -> bool {
    invoke!(bool, 0x305C8DCD79DA8B0F, group as u32, control as u32)
}

pub fn get_normal(group: Group, control: Control) -> f32 {
    invoke!(f32, 0xEC3C9B8D5327B563, group as u32, control as u32)
}

pub fn get_disabled_normal(group: Group, control: Control) -> f32 {
    invoke!(f32, 0x11E65974A982637C, group as u32, control as u32)
}